import 'package:flutter/material.dart';

class StackExampleScreen extends StatefulWidget {
  const StackExampleScreen({super.key});

  @override
  State<StackExampleScreen> createState() => _StackExampleScreenState();
}

class _StackExampleScreenState extends State<StackExampleScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Container(
      height: MediaQuery.of(context).size.height,
      width: MediaQuery.of(context).size.width,
      child: Stack(
        children: [
          SingleChildScrollView(
            child: Column(
              children: [
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hesdkfjcbsdhjllo"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Hello"),
                Text("Helldfvndjkfvo"),
                Text("Hesdkfjdsbjllo"),
                Text("Hello"),
              ],
            ),
          ),

          Positioned(
              bottom: 0,
              left: 0,
              right: 0,
              child: Column(
                children: [
                  Container(
                    height: 80,
                    color: Colors.red,
                  ),
                  Container(
                    height: 80,
                    color: Colors.green,
                  )
                ],
              )),
          // Positioned(
          //     bottom: 0,
          //     left: 1,
          //     right: 1,
          //     child: Container(
          //       height: 80,
          //       color: Colors.red,
          //     )),
          // Positioned(
          //     bottom: 0,
          //     left: 1,
          //     right: 1,
          //     child: Container(
          //       height: 80,
          //       color: Colors.green,
          //     )),
        ],
      ),
    ));
  }
}
